name: Test-Workflow

on:
  schedule:
    - cron: "0 17 * * *" # UTC timezone

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
      - name: Run code
        run: |
          echo "Hello Workflow!"
          whoami
          pwd
