name: Test-Workflow

on:
  schedule:
    - cron: "27 16 * * *"  # 4:27 pm [16:27] UTC

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run code
        run: |
          echo "Hello Workflow!"
          whoami
          pwd
