name: Test-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run code
        run: |
          echo "Hello Workflow!"
          whoami
          pwd
